config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }

  root to: 'items#index'

  resources :items, only: [ :show, :new, :create, :edit, :update ] do
    get :map, on: :collection
    patch :update_published, on: :member
    resources :upvotes, only: [ :create ]
    resources :bookmarks, only: [ :create ]
  end

  get :my_account, to: 'users#my_account'
  get :saved, to: 'users#saved'
  get :pending, to: 'users#pending'
  get :archive, to: 'users#archive'

  resources :users, only: [ :edit, :update ]

  resources :upvotes, only: [ :destroy ]

  resources :bookmarks, only: [ :destroy ]

  resources :hashtags, only: [ :index ]

  post 'twilio/sms'
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  def create
    item = Item.find(params[:item_id])
    upvote = Upvote.create(item: item, user: current_user)
    authorize upvote
    render partial: 'upvote', locals: { item: item }
  end

  def destroy
    upvote = Upvote.find(params[:id])
    authorize upvote
    item = upvote.item
    upvote.destroy
    render partial: 'upvote', locals: { item: item }
  end
end

app/views/upvotes/_upvote.html.erb
<% if policy(item).can_upvote? || !user_signed_in? %>
  <%= link_to item_upvotes_path(item), method: :post, class: 'btn btn-secondary', remote: user_signed_in?, data: { action: 'ajax:success->upvote#toggleUpvoted' } do %>
    <i class="fas fa-air-freshener"></i> <small><%= item.upvotes.count %></small>
  <% end %>
<% else %>
  <%= link_to upvote_path(item.upvotes.find_by(user: current_user)), method: :delete, class: 'btn btn-secondary btn-secondary-active', remote: true, data: { action: 'ajax:success->upvote#toggleUpvoted' } do %>
    <i class="fas fa-air-freshener"></i> <small><%= item.upvotes.count %></small>
  <% end %>
<% end %>