config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }

  root to: 'items#index'

  resources :items, only: [ :show, :new, :create, :edit, :update ] do
    get :map, on: :collection
    patch :update_published, on: :member
    resources :upvotes, only: [ :create ]
    resources :bookmarks, only: [ :create ]
  end

  get :my_account, to: 'users#my_account'
  get :saved, to: 'users#saved'
  get :pending, to: 'users#pending'
  get :archive, to: 'users#archive'

  resources :users, only: [ :edit, :update ]

  resources :upvotes, only: [ :destroy ]

  resources :bookmarks, only: [ :destroy ]

  resources :hashtags, only: [ :index ]

  post 'twilio/sms'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable
  has_many :items, dependent: :destroy
  has_many :upvotes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :saved_items, through: :bookmarks, source: :item


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.github_avatar = auth.info.image
      user.nickname = auth.info.nickname
      user.password = Devise.friendly_token[0,20]
    end
  end

  def picture_url
    if github_avatar.blank?
      return "https://eu.ui-avatars.com/api/?name=#{email}&background=ffa34d&color=fff"
    else
      return github_avatar
    end
  end

  rails_admin do
    list do
      field :nickname
      field :email
      field :items
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def my_account
  end

  def saved
  end

  def pending
  end

  def archive
  end

  def edit
  end

  def update
  end

  private

  def set_user
    @user = current_user
    authorize @user
  end
end

app/views/users/_sidebar.html.erb
<div class="card sticky-top-spaced">
  <div class="d-flex align-items-center p-3">
    <%= image_tag user.picture_url, class: "avatar-bordered avatar-xxl mr-3" %>
    <div>
      <p class="m-0"><strong><%= user.nickname %></strong></p>
      <p class="m-0 text-secondary"><small><%= user.email %></small></p>
    </div>
  </div>
  <div class="bg-light px-3 py-1">
    <span class="text-muted"><strong>Dashboard</strong></span>
  </div>
  <div>
    <%= link_to my_account_path, class: 'p-3 border-bottom d-flex w-100 justify-content-between align-items-center' do %>
      <div>
        <i class="fas fa-grip-horizontal text-muted mr-2"></i> Published Items
      </div>
      <span class="text-muted small"><%= current_user.items.published_items.count %></span>
    <% end %>
    <%= link_to saved_path, class: 'p-3 border-bottom d-flex w-100 justify-content-between align-items-center' do %>
      <div>
        <i class="fas fa-heart text-muted mr-2"></i> Saved Items
      </div>
      <span class="text-muted small"><%= current_user.saved_items.count %></span>
    <% end %>
    <%= link_to pending_path, class: 'p-3 border-bottom d-flex w-100 justify-content-between align-items-center' do %>
      <div>
        <i class="fas fa-pause-circle text-muted mr-2"></i> Pending Approvals
      </div>
      <span class="text-muted small"><%= current_user.items.unapproved_items.count %></span>
    <% end %>
    <%= link_to archive_path, class: 'p-3 d-block d-flex w-100 justify-content-between align-items-center' do %>
      <div>
        <i class="fas fa-archive text-muted mr-2"></i> Archived Items
      </div>
      <span class="text-muted small"><%= current_user.items.archived_items.count %></span>
    <% end %>
  </div>
  <div class="bg-light px-3 py-1">
    <span class="text-muted"><strong>Account</strong></span>
  </div>
  <div>
    <%= link_to "#", class: 'p-3 d-block border-bottom d-flex w-100 justify-content-between align-items-center' do %>
      <div>
      <i class="fas fa-cogs text-muted mr-2"></i> Edit Profile
      </div>
      <small class="badge badge-warning">Coming soon!</small>
    <% end %>
    <%= link_to destroy_user_session_path, method: :delete, class: 'p-3 border-bottom d-block' do %>
      <i class="fas fa-hand-peace text-muted mr-2"></i> Log out
    <% end %>
  </div>
</div>

app/views/users/archive.html.erb
<div class="bg-dark text-white">
  <div class="container pt-3 pb-5">
    <nav aria-label="breadcrumb ">
      <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item">
          <%= link_to "Home", root_path %>
        </li>
        <li class="breadcrumb-item">
          <%= link_to "My Account", my_account_path %>
        </li>
        <li class="breadcrumb-item active text-white" aria-current="page">
          Archived Items
        </li>
      </ol>
    </nav>
  </div>
</div>
<div class="container mt-n5 pb-4">
  <div class="row">
    <div class="col-lg-4">
      <%= render 'sidebar', user: @user, active: :pending %>
    </div>
    <div class="col-lg-8">
      <%= render 'items/list', title: "Archived Items", items: current_user.items.archived_items %>
    </div>
  </div>
</div>

app/views/users/my_account.html.erb
<div class="bg-dark text-white">
  <div class="container pt-3 pb-5">
    <nav aria-label="breadcrumb ">
      <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item">
          <%= link_to "Home", root_path %>
        </li>
        <li class="breadcrumb-item active text-white" aria-current="page">
          My Account
        </li>
      </ol>
    </nav>
  </div>
</div>
<div class="container mt-n5 pb-4">
  <div class="row">
    <div class="col-lg-4">
      <div class="card sticky-top-spaced">
        <div class="d-flex align-items-center p-3">
          <%= image_tag @user.picture_url, class: "avatar-bordered avatar-xxl mr-3" %>
          <div>
            <p class="m-0"><strong><%= @user.nickname %></strong></p>
            <p class="m-0 text-secondary"><small><%= @user.email %></small></p>
          </div>
        </div>
        <div class="bg-light px-3 py-1">
          <span class="text-muted"><strong>Dashboard</strong></span>
        </div>
        <div>
          <%= link_to "#", class: 'p-3 border-bottom d-flex w-100 justify-content-between align-items-center' do %>
            <div>
              <i class="fas fa-grip-horizontal text-muted mr-2"></i> Published Items
            </div>
            <span class="text-muted small"><%= current_user.items.published_items.count %></span>
          <% end %>
          <%= link_to "#", class: 'p-3 border-bottom d-flex w-100 justify-content-between align-items-center' do %>
            <div>
              <i class="fas fa-heart text-muted mr-2"></i> Saved Items <small class="text-muted">Coming soon!</small>
            </div>
            <span class="text-muted small">10</span>
          <% end %>
          <%= link_to "#", class: 'p-3 border-bottom d-flex w-100 justify-content-between align-items-center' do %>
            <div>
              <i class="fas fa-pause-circle text-muted mr-2"></i> Pending Approvals <small class="text-muted">Coming soon!</small>
            </div>
            <span class="text-muted small"><%= current_user.items.unapproved_items.count %></span>
          <% end %>
          <%= link_to "#", class: 'p-3 d-block d-flex w-100 justify-content-between align-items-center' do %>
            <div>
              <i class="fas fa-archive text-muted mr-2"></i> Archived Items <small class="text-muted">Coming soon!</small>
            </div>
            <span class="text-muted small">10</span>
          <% end %>
        </div>
        <div class="bg-light px-3 py-1">
          <span class="text-muted"><strong>Account</strong></span>
        </div>
        <div>
          <%= link_to "#", class: 'p-3 border-bottom d-block' do %>
            <i class="fas fa-cogs text-muted mr-2"></i> Edit Profile
          <% end %>
          <%= link_to "#", class: 'p-3 border-bottom d-block' do %>
            <i class="fas fa-hand-peace text-muted mr-2"></i> Log out
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-8">
      <div class="text-white pt-2 d-none d-lg-block">
        <h5>Published Items</h5>
      </div>
      <div class="pt-2">
        <% if current_user.items.published_items.any? %>
          <% current_user.items.published_items.each do |item| %>
            <%= render 'items/list_item', item: item %>
          <% end %>
        <% else %>
          <p class="text-muted pt-3">No items yet, <%= link_to "add one here", new_item_path %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/pending.html.erb
<div class="bg-dark text-white">
  <div class="container pt-3 pb-5">
    <nav aria-label="breadcrumb ">
      <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item">
          <%= link_to "Home", root_path %>
        </li>
        <li class="breadcrumb-item">
          <%= link_to "My Account", my_account_path %>
        </li>
        <li class="breadcrumb-item active text-white" aria-current="page">
          Pending Approvals
        </li>
      </ol>
    </nav>
  </div>
</div>
<div class="container mt-n5 pb-4">
  <div class="row">
    <div class="col-lg-4">
      <%= render 'sidebar', user: @user, active: :pending %>
    </div>
    <div class="col-lg-8">
      <%= render 'items/list', title: "Pending Approvals", items: current_user.items.unapproved_items %>
    </div>
  </div>
</div>

app/views/users/saved.html.erb
<div class="bg-dark text-white">
  <div class="container pt-3 pb-5">
    <nav aria-label="breadcrumb ">
      <ol class="breadcrumb bg-dark">
        <li class="breadcrumb-item">
          <%= link_to "Home", root_path %>
        </li>
        <li class="breadcrumb-item">
          <%= link_to "My Account", my_account_path %>
        </li>
        <li class="breadcrumb-item active text-white" aria-current="page">
          Saved Items
        </li>
      </ol>
    </nav>
  </div>
</div>
<div class="container mt-n5 pb-4">
  <div class="row">
    <div class="col-lg-4">
      <%= render 'sidebar', user: @user, active: :saved %>
    </div>
    <div class="col-lg-8">
      <%= render 'items/list', title: "Saved Items", items: current_user.saved_items %>
    </div>
  </div>
</div>