config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }

  root to: 'items#index'

  resources :items, only: [ :show, :new, :create, :edit, :update ] do
    get :map, on: :collection
    patch :update_published, on: :member
    resources :upvotes, only: [ :create ]
    resources :bookmarks, only: [ :create ]
  end

  get :my_account, to: 'users#my_account'
  get :saved, to: 'users#saved'
  get :pending, to: 'users#pending'
  get :archive, to: 'users#archive'

  resources :users, only: [ :edit, :update ]

  resources :upvotes, only: [ :destroy ]

  resources :bookmarks, only: [ :destroy ]

  resources :hashtags, only: [ :index ]

  post 'twilio/sms'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="bg-dark">
  <div class="container py-4">
    <p class="text-white mb-0">Created by <%= link_to "Arthur", "https://github.com/arthur-littm" %>.</p>
    <span class="small text-muted">Ⓒ 2020 Scubo.life, All rights reserved.</span>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
      <%= image_tag "logo.svg", class: 'mr-2' %> <strong>Scubo.life</strong>
    <% end %>

    <div class="d-flex align-items-center">
      <% if user_signed_in? %>
        <%= link_to "Add Item", new_item_path, class: "btn btn-light btn-sm px-3" %>
        <div class="ml-3 dropdown">
          <%= image_tag current_user.picture_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <h6 class="dropdown-header">Menu</h6>
            <%= link_to "My Account", my_account_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <% if current_user.admin %>
              <h6 class="dropdown-header">Admin</h6>
              <%= link_to "Dashboard", rails_admin_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
      <% else %>
        <%= link_to omniauth_authorize_path(:user, :github), class: "btn btn-primary" do %>
          Sign In <i class="fab fa-github ml-2"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_panel.html.erb
<div class="card p-3 mb-3">
  <div class="d-flex justify-content-between align-items-center">
    <strong><%= title %></strong>
  </div>
  <hr class="my-2">
  <% collection.each do |resource| %>
    <% symbol = resource.class.name.parameterize.to_sym %>
    <% active = params[symbol].to_i == resource.id %>
    <%= link_to request.params.merge(symbol => active ? nil : resource.id, page: nil), class: "panel-item rounded p-1 #{'bg-secondary text-white' if active}"  do  %>
      <div class="d-flex align-items-center justify-content-between">
        <div>
          <% if resource.is_a?(Category) %>
            <span class="mr-2">
              <%= resource.emoji %>
            </span>
          <% end %>
          <span>
            <%= resource.name %>
          </span>
        </div>
        <small class="pr-2 <%=  active ? 'text-white' : 'text-muted' %>"><%= resource.items.published_items.count %></small>
      </div>
    <% end %>
  <% end %>
</div>