config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }

  root to: 'items#index'

  resources :items, only: [ :show, :new, :create, :edit, :update ] do
    get :map, on: :collection
    patch :update_published, on: :member
    resources :upvotes, only: [ :create ]
    resources :bookmarks, only: [ :create ]
  end

  get :my_account, to: 'users#my_account'
  get :saved, to: 'users#saved'
  get :pending, to: 'users#pending'
  get :archive, to: 'users#archive'

  resources :users, only: [ :edit, :update ]

  resources :upvotes, only: [ :destroy ]

  resources :bookmarks, only: [ :destroy ]

  resources :hashtags, only: [ :index ]

  post 'twilio/sms'
end

app/models/item.rb
class Item < ApplicationRecord
  MAX_CHARS_NAME = 36
  MAX_CHARS_DESC = 160
  MAX_IMAGE_BYTE_SIZE = 10_000_000

  belongs_to :category
  belongs_to :hashtag
  belongs_to :user
  belongs_to :city, optional: true

  has_many :upvotes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :upvoters, through: :upvotes, source: :user
  has_many :bookmarkers, through: :bookmarks, source: :user

  validates :name, :description, :address, presence: true
  validates :name, length: { minimum: 2, maximum: MAX_CHARS_NAME }
  validates :description, length: { minimum: 2, maximum: MAX_CHARS_DESC }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  scope :filter_by_category, -> (category_id) { where category_id: category_id }
  scope :filter_by_hashtag, -> (hashtag_id) { where hashtag_id: hashtag_id }
  scope :filter_by_city, -> (city_id) { where city_id: city_id }

  has_one_attached :photo
  validate :photo_present
  validate :photo_size, if: Proc.new { |p| p.photo.attached? }

  after_create :notify_subscribers

  scope :published_items, -> { where(approved: true).where(published: true) }
  scope :unapproved_items, -> { where(approved: false) }
  scope :archived_items, -> { where(published: false) }

  def photo_key
    if photo.attached?
      photo.key
    else
      'images_ydlatu'
    end
  end

  def notify_subscribers
    return unless Rails.env.production?
    approval_url = "https://www.scubo.life/admin/item?model_name=item&f%5Bapproved%5D%5B50286%5D%5Bv%5D=false"
    client = Twilio::REST::Client.new
    subscriber = Subscriber.first
    client.messages.create(
        from: "+442033897305",
        to: subscriber.phone_number,
        body: "New item to approve! \n  Author: #{self.user.nickname} \n Item: #{self.name} \n Description: #{self.description} \n \n #{approval_url}"
    )
  end

  private

  def photo_size
    if photo&.byte_size > MAX_IMAGE_BYTE_SIZE
      errors.add(:photo, 'is too large (10MB)')
    end
  end

  def photo_present
    unless photo&.attached?
      errors.add(:photo, 'is missing')
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :map, :show ]
  before_action :set_categories, only: [ :index, :new, :create, :map, :edit, :update ]
  before_action :set_hashtags, only: [ :index, :map ]
  before_action :set_cities, only: [ :index, :map ]

  def index
    @items = sort(policy_scope(Item))
    @items = @items.where(user_id: params[:user]) if params[:user]
    @items = @items.filter_by_category(params[:category]) if params[:category].present?
    @items = @items.filter_by_hashtag(params[:hashtag]) if params[:hashtag].present?
    @items = @items.filter_by_city(params[:city]) if params[:city].present?

    @items = @items.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    authorize @item
    @markers = [ { lat: @item.latitude, lng: @item.longitude} ]
    render partial: 'items/show', locals: { item: @item }
  end

  def map
    authorize(Item)
    @items = policy_scope(Item).geocoded
    @items = @items.filter_by_category(params[:category]) if params[:category].present?
    @items = @items.filter_by_hashtag(params[:hashtag]) if params[:hashtag].present?
    @markers = @items.map do |item|
      {
        lat: item.latitude,
        lng: item.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { item: item })
      }
    end
  end

  def new
    @item = Item.new
    authorize @item
    @markers = []
  end

  def create
    @item = Item.new(item_params)
    authorize @item
    @item.user = current_user
    @item.hashtag = find_or_create_hashtag(params.dig(:item, :hashtag, :name))
    @item.city = find_or_create_city(params.dig(:item, :city, :name))
    @item.approved = true if current_user.admin
    if @item.save
      flash[:notice] = "Item submitted for approval, wait a few minutes."
      redirect_to my_account_path
    else
      @item.hashtag = nil
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    authorize @item
    @markers = [ { lat: @item.latitude, lng: @item.longitude} ]
  end

  def update
    @item = Item.find(params[:id])
    authorize @item
    @item.hashtag = find_or_create_hashtag(params.dig(:item, :hashtag, :name))
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def update_published
    @item = Item.find(params[:id])
    authorize @item
    @item.update(published: params[:published])
    flash[:notice] = "Item has been #{@item.published ? 'published' : 'archived'}"
    redirect_to my_account_path
  end

  private

  def sort(items)
    if params[:sort] == 'newest'
      items.joins(:user)
        .order(created_at: :desc)
    else
      items.left_joins(:upvotes)
        .group(:id)
        .order('COUNT(upvotes.id) DESC')
    end
  end

  def find_or_create_city(string)
    return if string.blank?
    return City.find_or_create_by(name: string)
  end

  def find_or_create_hashtag(string)
    return if string.blank?
    formatted_hashtag = Hashtag.format(string)
    return Hashtag.find_or_create_by(name: formatted_hashtag)
  end

  def item_params
    params.require(:item).permit(
      :name,
      :description,
      :category_id,
      :address,
      :photo,
      :published)
  end
end

app/views/items/_form.html.erb
<%= simple_form_for(item) do |f| %>

  <div data-controller='counter'>
    <%= f.input :name,
    label: false,
    placeholder: 'Name',
    input_html: { data: { target: 'counter.input', action: 'keyup->counter#updateCounter' } },
    hint: "<span data-target='counter.counter' data-max='#{Item::MAX_CHARS_NAME}''>#{Item::MAX_CHARS_NAME} characters left.</span>".html_safe %>
  </div>

  <div class="typeahead" data-controller='typeahead'>
    <%= f.simple_fields_for :hashtag do |h| %>
      <%= h.input :name,
      hint: "",
      label: false,
      hint: "Does it even count if you don't #hashtag it?",
      placeholder: "Hashtag",
      input_html: { value: item.hashtag&.name, data: { target: 'typeahead.input', action: 'keyup->typeahead#updateResults blur->typeahead#closeResults' } } %>
      <div class="typeahead-results w-100 card" data-target='typeahead.results'>
      </div>
    <% end %>
  </div>

  <div data-controller='counter'>
    <%= f.input :description,
    label: false,
    placeholder: 'Description',
    input_html: { data: { target: 'counter.input', action: 'keyup->counter#updateCounter' } },
    hint: "<span data-target='counter.counter' data-max='#{Item::MAX_CHARS_DESC}''>#{Item::MAX_CHARS_DESC} characters left.</span>".html_safe %>
  </div>

  <div data-controller='autocomplete'>
    <%= f.input :address,
    label: false,
    placeholder: "Address",
    hint: 'Where is it?',
    input_html: { data: { target: 'autocomplete.input' } } %>


    <%= f.simple_fields_for :city do |c| %>
      <%= c.input :name,
          input_html: { value: item.city&.name, readonly: :true, data: { target: 'autocomplete.city' } },
          label: false,
          placeholder: "City" %>
    <% end %>
  </div>

  <hr>

  <fieldset class="form-group radio_buttons required item_category">
    <input type="hidden" name="item[category_id]" value="">
    <div class="checkboxes" data-controller="checkboxes">
      <% @categories.each do |category| %>
        <input class="d-none" type="radio" value="<%= category.id %>" name="item[category_id]" id="item_category_id_<%= category.id %>">
        <label class="card p-3 m-0 text-center" for="item_category_id_<%= category.id %>" data-action="click->checkboxes#updateCheckbox" data-target="checkboxes.checkbox">
          <h2><%= category.emoji %></h2>
          <p class="m-0"><%= category.name %></p>
        </label>
      <% end %>
    </div>
    <% if item.errors[:category].any? %>
      <div class="small text-danger mt-2">Please select a category.</div>
    <% end %>

  </fieldset>

  <hr>

  <div data-controller='photo-preview'>
    <% if item.photo.attached? %>
      <% path = cl_image_path item.photo.key %>
    <% else %>
      <% path = "" %>
    <% end %>

    <%= image_tag path, width: 300, class: "#{'d-none' if path.blank?} rounded mb-3", data: { target: "photo-preview.image" } %>
    <%= f.input :photo, as: :file, input_html: { class: 'd-none', data: { action: 'change->photo-preview#displayPreview' } }, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary mb-3" %>
<% end %>

app/views/items/_info_window.html.erb
<%= cl_image_tag item.photo_key, class: "card-img img-fit", alt: item.name, height: 160, role: "button", data: { toggle: "modal", target: "#item#{ item.id }" } %>
<div class="px-2 card-content">
  <%= image_tag item.user.picture_url, class: "avatar-bordered" %>
</div>
<div class="d-flex justify-content-between align-items-start">
  <div>
    <p class="m-0"><strong><%= item.name %> <%= item.category.emoji %></strong></p>
    <span class="text-secondary small"><%= link_to item.hashtag.name, root_path(hashtag: item.hashtag) %></span>
  </div>
  <%= link_to item_upvotes_path(item), method: :post, class: 'btn btn-secondary' do %>
    <i class="fas fa-air-freshener"></i> <small><%= item.upvotes.count %></small>
  <% end %>
</div>

app/views/items/_item.html.erb
<div class="card p-3">
  <%= cl_image_tag item.photo_key, class: "card-img img-fit", alt: item.name, height: 160, role: "button", data: { action: "click->modal#open", item: item.id } %>
  <div class="px-2 card-content">
    <%= image_tag item.user.picture_url, class: "avatar-bordered" %>
  </div>
  <div class="d-flex justify-content-between align-items-start">
    <div>
      <p class="m-0"><strong><%= item.name %></strong></p>
      <div class="d-flex align-items-center">
        <span class="pr-1"><%= item.category.emoji %></span>
        <span class="text-secondary small"><%= link_to item.hashtag.name, root_path(hashtag: item.hashtag) %></span>
      </div>
    </div>
    <div class="flex-shrink-0" data-controller="upvote" data-target="upvote.upvoteLink">
      <%= render 'upvotes/upvote', item: item %>
    </div>
  </div>
</div>

app/views/items/_list.html.erb
<div class="text-white pt-2 d-none d-lg-block">
  <h5><%= title %></h5>
</div>
<div class="pt-2">
  <% if items.any? %>
    <% items.each do |item| %>
      <%= render 'items/list_item', item: item %>
    <% end %>
  <% else %>
    <% if title == 'Pending Approvals' %>
      <p class="text-muted pt-3">No items with pending approval, <%= link_to "add one here", new_item_path %></p>
    <% elsif title == 'Archived Items' %>
      <p class="text-muted pt-3">No items in the archive.</p>
    <% elsif title == 'Saved Items' %>
      <p class="text-muted pt-3">No saved items, <%= link_to "browse items here", root_path %>.</p>
    <% end %>
  <% end %>
</div>

app/views/items/_list_item.html.erb
<div class="d-md-flex justify-content-between  my-3">
  <%= cl_image_tag item.photo_key, class: "rounded img-fit mr-3 list-img mb-3 mb-md-0", alt: item.name %>
  <div class="flex-grow-1">
    <div class="d-flex align-items-start">
      <div class="flex-grow-1 flex-shrink-1">
        <p class="mb-2"><strong><%= item.name %></strong></p>
      </div>
      <div class="d-flex align-items-center">
        <% if policy(item).edit? %>

          <% if item.published && item.approved %>
            <%= link_to "Edit", edit_item_path(item), class: 'btn-sm mr-2'  %>
            <%= link_to "Archive", update_published_item_path(item, published: false), method: :patch, class: 'btn btn-danger btn-sm'  %>
          <% elsif !item.published && item.approved %>
            <%= link_to "Restore", update_published_item_path(item, published: true), method: :patch, class: 'btn btn-secondary btn-sm'  %>
          <% else %>
            <span class="badge badge-secondary">Waiting for approval</span>
          <% end %>
        <% end %>

      </div>
    </div>
    <div class="small"><span class="text-muted">Category:</span> <span class="text-secondary"><%= item.category.emoji %> <%= item.category.name %></span></div>
    <div class="small"><span class="text-muted">Hashtag:</span> <span class="text-secondary"><%= item.hashtag.name %></span></div>
    <div class="small"><span class="text-muted">City:</span> <span class="text-secondary"><%= item.city&.name %></span></div>
    <p class="mt-2"><%= item.description %></p>
  </div>
</div>
<hr>

app/views/items/_show.html.erb
<div class="container-fluid">
  <div class="d-flex align-items-center justify-content-between">
    <div>
      <%= image_tag item.user.picture_url, class: "avatar-bordered avatar-large mr-2" %>
      <span>By <strong><%= item.user.nickname %></strong> (<%= link_to pluralize(item.user.items.count, 'item'), root_path(user: item.user.id) %>)</span>
    </div>

    <div data-controller="upvote" data-target="upvote.upvoteLink">
      <%= render 'upvotes/upvote', item: item %>
    </div>
  </div>

  <%= cl_image_tag item.photo_key, class: "w-100 rounded img-fit my-3", alt: item.name, height: 300, role: "button", data: { toggle: "modal", target: "#item#{ item.id }" } %>

  <div class="row">
    <div class="col-12 col-lg-6">
      <div class="bg-light rounded p-3 mb-3">
        <p class="m-0"><strong><%= item.name %> <%= item.category.emoji %></strong></p>
        <span class="text-secondary"><%= link_to item.hashtag.name, root_path(hashtag: item.hashtag) %></span>
        <p class="mt-2 mb-0"><%= item.description %></p>
      </div>
      <span class="text-muted">Who else thought this was fresh?</span>
      <div class="d-flex align-items-center mt-2">
        <% upvoters = item.upvoters.uniq %>
        <% if upvoters.empty? %>
          <p>No upvotes yet 😢</p>
        <% else %>
          <% upvoters[0, 5].each do |user| %>
            <%= image_tag user.picture_url, class: "avatar-bordered mr-n2" %>
          <% end %>
          <% reminder = upvoters[5..-1]&.count %>
          <% if reminder && reminder.positive? %>
            <strong class='ml-3 text-secondary'>+ <%= reminder %> <i class="fas fa-air-freshener"></i></strong>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-lg-6 mt-3 mt-lg-0" data-controller='map'>
      <div id="map"
           class="rounded overflow-hidden"
           style="width: 100%; height: 240px;"
           data-target="map.map"
           data-markers="<%= @markers.to_json %>"
           data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
  <hr>
  <div class="d-flex justify-content-between align-items-center">
    <div class="d-flex align-items-center">
      <div data-controller="bookmark" data-target="bookmark.bookmarkLink">
        <%= render 'bookmarks/bookmark', item: item %>
      </div>
      <% if policy(item).edit? %>
        <%= link_to "Edit", edit_item_path(item), class: 'btn btn-light mr-2' %>
      <% end %>
    </div>
    <div>
      <button type="button" class="btn btn-light" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<div class="container py-3">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to "Home", root_path %>
      </li>
      <li class="breadcrumb-item">
        <%= link_to "Items", root_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= @item.name %>
      </li>
    </ol>
  </nav>
  <div class="row" data-controller="map">
    <div class="col-12 col-md-8">
      <h2>Edit your Item</h2>
      <p class="text-muted">Items are things you’d like your friends to know about, like a cool bar, a tasty pork belly, etc.</p>
      <%= render "form", item: @item %>
    </div>
    <div class="col-12 col-md-4">
      <div id="map"
           class="rounded overflow-hidden"
           style="width: 100%; height: 600px;"
           data-target="map.map"
           data-markers="<%= @markers.to_json %>"
           data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="container py-3 full-height" data-controller="modal">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to "Home", root_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        Items
      </li>
    </ol>
  </nav>

  <div class="row">
    <div class="d-none d-sm-block col-sm-4 col-lg-3">
      <div class="sticky-top-spaced">
        <%= render 'shared/panel', collection: @categories, title: "Categories" %>
        <%= render 'shared/panel', collection: @cities, title: "Cities" %>
        <%= render 'shared/panel', collection: @hashtags, title: "Popular hashtags" %>
      </div>
    </div>
    <div class="col-12 col-sm-8 col-lg-9">
      <div class="d-flex justify-content-between align-items-center mb-2 flex-wrap">
        <div class="d-flex align-items-center">
          <span class="text-muted small mr-2 flex-shrink-0">
            <%= page_entries_info @items %>
          </span>
          <% if params.has_key?(:category) || params.has_key?(:hashtag) || params.has_key?(:user) || params.has_key?(:city) || params.has_key?(:around_me) %>
            <%= link_to "Clear filters", root_path, class: "small" %>
          <% end %>
        </div>

        <div class="d-flex align-items-center flex-wrap my-2 my-md-0" data-controller='sort'>
          <%= link_to "Map view", map_items_path, class: "small mr-2 flex-shrink-0" %>
          <select class="form-control w-auto form-control-sm" data-action="change->sort#refresh">
            <option value="popular" <%= 'selected' if params['sort'] != 'newest' %>>Sort by popularity</option>
            <option value="newest" <%= 'selected' if params['sort'] == 'newest' %>>Sort by newest</option>
          </select>
        </div>
      </div>
      <div class="cards">
        <% @items.each do |item| %>
          <%= render item %>
        <% end %>
      </div>
      <div class="p-3 d-flex justify-content-center">
        <%= paginate @items %>
      </div>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" data-target="modal.modal" tabindex="-1" role="dialog" aria-labelledby="itemModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-body" data-target="modal.container">
          <div class="text-center py-5">
            <i class="fas fa-spinner fa-pulse display-4 text-muted"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/map.html.erb
<div class="container py-3">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to "Home", root_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        Items
      </li>
    </ol>
  </nav>

  <div class="row"  data-controller="map">
    <div class="d-none d-sm-block col-sm-4 col-lg-3">
      <div class="sticky-top-spaced">
        <%= render 'shared/panel', collection: @categories, title: "Categories" %>
        <%= render 'shared/panel', collection: @cities, title: "Cities" %>
        <%= render 'shared/panel', collection: @hashtags, title: "Popular hashtags" %>
      </div>
    </div>
    <div class="col-12 col-sm-8 col-lg-9">
      <div class="d-flex justify-content-between align-items-center mb-2">
        <div>
          <% if params.has_key?(:category) || params.has_key?(:hashtag) %>
            <%= link_to "Clear filters", root_path, class: "small" %>
          <% end %>
        </div>
        <div>
          <%= link_to "List view", root_path, class: "small" %>
        </div>
      </div>
      <div id="map"
           class="rounded overflow-hidden"
           style="width: 100%; height: 500px;"
           data-markers="<%= @markers.to_json %>"
           data-target="map.map"
           data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>

</div>

app/views/items/new.html.erb
<div class="container py-3">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to "Home", root_path %>
      </li>
      <li class="breadcrumb-item">
        <%= link_to "Items", root_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        Add Item
      </li>
    </ol>
  </nav>
  <div class="row" data-controller="map">
    <div class="col-12 col-md-8">
      <h2>Add an Item</h2>
      <p class="text-muted">Items are things you’d like your friends to know about, like a cool bar, a tasty pork belly, etc.</p>
      <%= render "form", item: @item %>
    </div>
    <div class="col-12 col-md-4">
      <div id="map"
           class="rounded overflow-hidden"
           style="width: 100%; height: 600px;"
           data-target="map.map"
           data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>